### ISSUE TITLE
IMDS routing doesn't persist on MacOS Big Sur

### ISSUE THREAD

**Issue by patricksanders** [Netflix/weep#66]
Weep includes [plist files](https://github.com/Netflix/weep/tree/master/extras) that are meant to create persistent configurations to route `169.254.169.254:80` (the EC2 IMDS address) to `127.0.0.1:9091`. The manual commands for these configurations seem to work correctly, but the plists do not make the configurations persist after a reboot.

(Theoretical) reproduction steps:
1. Follow [the documentation steps](https://hawkins.gitbook.io/consoleme/weep-cli/advanced-configuration/routing-for-metadata-service) (i.e. place the `plist` files in `/Library/LaunchDaemons` and reboot)
2. Attempt to `curl http://169.254.169.254/latest/meta-data/iam/security-credentials`

**Comment by MorganOnBass** [comment]
I've found that editing /etc/pf.conf persists, but apparently that can get overwritten by macos upgrades. We could probably coax weep into checking for the nat rule at start and load the plist if it's not found?

**Comment by patricksanders** [comment]
I did some digging, and I think I have a way forward here. I'm thinking Weep could handle this with something like `sudo weep configure` (`sudo` is required, unfortunately).

## Create loopback alias
Invoke `ifconfig lo0 169.254.169.254 alias`

This should persist across reboots (need to verify)

## Configure `pf` to redirect traffic to weep

Create `/etc/pf.anchors/redirection` with contents:
```
rdr pass on lo0 inet proto tcp from any to 169.254.169.254 port 80 -> 127.0.0.1 port 9091
```

Update `/etc/pf.conf` with contents:
```
scrub-anchor "com.apple/*"
nat-anchor "com.apple/*"
rdr-anchor "com.apple/*"
rdr-anchor "redirection"  # added by weep
dummynet-anchor "com.apple/*"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
load anchor "redirection" from "/etc/pf.anchors/redirection"  # added by weep
```

This should persist across reboots, but probably not across OS upgrades.

## Enable `pf` at startup

`/Library/LaunchDaemons/com.user.pfctl.plist`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Enabled</key>
	<false/>
	<key>Label</key>
	<string>com.user.pfctl</string>
	<key>WorkingDirectory</key>
	<string>/var/run</string>
	<key>Program</key>
	<string>/sbin/pfctl</string>
	<key>ProgramArguments</key>
	<array>
		<string>pfctl</string>
		<string>-E</string>
		<string>-f</string>
		<string>/etc/pf.conf</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

Invoke `launchctl load /Library/LaunchDaemons/com.user.pfctl.plist`. This should enable `pf` immediately with the new configuration.
